#!/bin/sh
# File generated by ocamlbuild

cd '/home/fati/UPMC/Stage_été_2018/2018_IRILL_INTERNSHIP/programs/week_4_temps_d_exec'

rm -f bench.cmi
rm -f bench.cmo
rm -f js_affiche.cmi
rm -f js_affiche.cmo
rm -f reload_js_affiche.cmi
rm -f reload_js_affiche.cmo
# Also clean the script itself
rm -f '/home/fati/UPMC/Stage_été_2018/2018_IRILL_INTERNSHIP/programs/week_4_temps_d_exec/_build/sanitize.sh'
