#!/bin/sh
# File generated by ocamlbuild

cd '/home/fati/UPMC/Stage_été_2017/2018_IRILL_INTERSHIP/progconc'

rm -f lwt_obrowser.cma
rm -f lwt_obrowser.cmi
rm -f lwt_obrowser.cmo
rm -f lwt_preemptive.cmi
rm -f lwt_preemptive.cmo
# Also clean the script itself
rm -f '/home/fati/UPMC/Stage_été_2017/2018_IRILL_INTERSHIP/progconc/_build/sanitize.sh'
