// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

for(var x = 1; x <= 10; ++x){
  var file = Pervasives.open_out("java_script_bs_times.txt");
  var x$1 = performance.now();
  var y = performance.now();
  Pervasives.output_value(file, y - x$1);
  location.reload();
}

/*  Not a pure module */
