// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var isEnterKey = (
    function (e) {
      return e.which === 13;
    }
  );

var Event = /* module */[/* isEnterKey */isEnterKey];

var Element = /* module */[];

var Document = /* module */[];

var Window = /* module */[];

var Form = /* module */[];

function clicked(a) {
  if (a.innerHTML === "clicked !") {
    a.innerHTML = "click me !";
    return /* () */0;
  } else {
    a.innerHTML = "clicked !";
    return /* () */0;
  }
}

function envoie($$this) {
  return "<div> Welcome" + ($$this.firstname.value + (" " + ($$this.lastname.value + "</div>")));
}

exports.Event = Event;
exports.Element = Element;
exports.Document = Document;
exports.Window = Window;
exports.Form = Form;
exports.clicked = clicked;
exports.envoie = envoie;
/* isEnterKey Not a pure module */
