// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Lwt = require("bs-lwt/lwt/src/core/lwt.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var isEnterKey = (
    function (e) {
      return e.which === 13;
    }
  );

var Event = /* module */[/* isEnterKey */isEnterKey];

var Element = /* module */[];

var Document = /* module */[];

var Window = /* module */[];

function perim(n) {
  return n * 2.0 * 3.14;
}

function puis(x) {
  return x + 2.0;
}

function nbr_cons2(n, deg) {
  var r = 1;
  while(r < 10000000) {
    Pervasives.print_int(r);
    Pervasives.print_string(" ");
    r = r + 1 | 0;
  };
  return Lwt.$$return((deg.innerHTML = perim(n), /* () */0));
}

function nbr_voys2(n, deg) {
  var r = 1;
  while(r < 1000000) {
    Pervasives.print_int(r);
    Pervasives.print_string(" ");
    r = r + 1 | 0;
  };
  return Lwt.$$return((deg.innerHTML = perim(n), /* () */0));
}

Lwt.$$return((alert("hello"), /* () */0));

function clicked() {
  document.getElementById("clickme").disabled = true;
  return /* () */0;
}

Lwt.bind(Lwt.$$return(document.getElementById("clickme").value), (function (s) {
        return Lwt.bind(Lwt.join(/* :: */[
                        nbr_voys2(s, document.getElementById("count")),
                        /* :: */[
                          nbr_cons2(s, document.getElementById("count2")),
                          /* [] */0
                        ]
                      ]), (function () {
                      return Lwt.$$return((document.getElementById("clickme").disabled = false, /* () */0));
                    }));
      }));

exports.Event = Event;
exports.Element = Element;
exports.Document = Document;
exports.Window = Window;
exports.perim = perim;
exports.puis = puis;
exports.nbr_cons2 = nbr_cons2;
exports.nbr_voys2 = nbr_voys2;
exports.clicked = clicked;
/* isEnterKey Not a pure module */
