// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var a = performance.now();
alert("Hello");
var b = performance.now();
alert('It took ' + (b - a) + ' ms.');


/*  Not a pure module */
