// Generated by js_of_ocaml 3.1.0
(function(g){"use strict";var
aq=" : flags Open_text and Open_binary are not compatible",N=".",ap=224,az="Sys_error",M="+",aG="Invalid_argument",x=1024,ay=57343,aF=512,aE="End_of_file",s=" ",P="e",aD="Failure",ak="Undefined_recursive_module",ax=" : flags Open_rdonly and Open_wronly are not compatible",aw="([^/]*)",t="-",ao="Stack_overflow",c="",av=1.8,f=128,O="^",aj=56320,as=" : file already exists",at=240,au=2048,p="0",b=248,E="erreur",an="Not_found",ai="Assert_failure",m="/",aB="Sys_blocked_io",aC="fd ",ar="Out_of_memory",am="Match_failure",al="static/",aA="Division_by_zero";function
W(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
V(b,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==b.length)return e.apply(null,b);var
f=c;for(;0<a;d+=x,a-=x)f+=e.apply(null,W(b,d,Math.min(a,x)));return f}function
S(b){if(g.Uint8Array)var
c=new(g.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
u(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?V(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?V(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)S(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
bN(c,e){var
d=c.length,b=new
Array(d+1),a=0;for(;a<d;a++)b[a]=c[a];b[a]=e;return b}function
F(b,a){if(b.fun)return F(b.fun,a);var
c=b.length,d=a.length,e=c-d;if(e==0)return b.apply(null,a);else
if(e<0)return F(b.apply(null,W(a,0,c)),W(a,c,d-c));else
return function(c){return F(b,bN(a,c))}}function
bD(b,a){if(a.repeat)return a.repeat(b);var
d=c,e=0;if(b==0)return d;for(;;){if(b&1)d+=a;b>>=1;if(b==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
aJ(a){if(a.t==2)a.c+=bD(a.l-a.c.length,"\0");else
a.c=V(a.c,0,a.c.length);a.t=0}function
aL(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
bJ(g){for(var
l=c,d=c,i,h,j,a,b=0,k=g.length;b<k;b++){h=g.charCodeAt(b);if(h<f){for(var
e=b+1;e<k&&(h=g.charCodeAt(e))<f;e++);if(e-b>aF){d.substr(0,1);l+=d;d=c;l+=g.slice(b,e)}else
d+=g.slice(b,e);if(e==k)break;b=e}a=1;if(++b<k&&((j=g.charCodeAt(b))&-64)==f){i=j+(h<<6);if(h<ap){a=i-12416;if(a<f)a=1}else{a=2;if(++b<k&&((j=g.charCodeAt(b))&-64)==f){i=j+(i<<6);if(h<at){a=i-925824;if(a<au||a>=55295&&a<57344)a=2}else{a=3;if(++b<k&&((j=g.charCodeAt(b))&-64)==f&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),aj+(a&1023));else
d+=String.fromCharCode(a);if(d.length>x){d.substr(0,1);l+=d;d=c}}return l+d}function
bI(a){switch(a.t){case
9:return a.c;default:aJ(a);case
0:if(aL(a.c)){a.t=9;return a.c}a.t=8;case
8:return bJ(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return bI(this)};function
bB(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
U(c,b){bB(c,a(b))}var
d=[0];function
T(a){U(d.Invalid_argument,a)}function
q(a){if(a<0)T("String.create");return new
n(a?2:9,c,a)}function
bp(a){U(d.Failure,a)}function
R(a){if((a.t&6)!=0)aJ(a);return a.c}function
aK(a){var
b;a=R(a);b=+a;if(a.length>0&&b===b)return b;a=a.replace(/_/g,c);b=+a;if(a.length>0&&b===b||/^[+-]?nan$/i.test(a))return b;var
d=/^ *([+-]?)0x([0-9a-f]+)\.?([0-9a-f]*)p([+-]?[0-9]+)/i.exec(a);if(d){var
e=d[3].replace(/0+$/,c),g=parseInt(d[1]+d[2]+e,16),f=(d[4]|0)-4*e.length;b=g*Math.pow(2,f);return b}if(/^\+?inf(inity)?$/i.test(a))return Infinity;if(/^-inf(inity)?$/i.test(a))return-Infinity;bp("float_of_string")}function
bz(d){d=R(d);var
e=d.length;if(e>31)T("format_int: format too long");var
a={justify:M,signstyle:t,filler:s,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
c=0;c<e;c++){var
b=d.charAt(c);switch(b){case"-":a.justify=t;break;case"+":case" ":a.signstyle=b;break;case"0":a.filler=p;break;case"#":a.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":a.width=0;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.width=a.width*10+b;c++}c--;break;case".":a.prec=0;c++;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.prec=a.prec*10+b;c++}c--;case"d":case"i":a.signedconv=true;case"u":a.base=10;break;case"x":a.base=16;break;case"X":a.base=16;a.uppercase=true;break;case"o":a.base=8;break;case"e":case"f":case"g":a.signedconv=true;a.conv=b;break;case"E":case"F":case"G":a.signedconv=true;a.uppercase=true;a.conv=b.toLowerCase();break}}return a}function
bq(b,g){if(b.uppercase)g=g.toUpperCase();var
f=g.length;if(b.signedconv&&(b.sign<0||b.signstyle!=t))f++;if(b.alternate){if(b.base==8)f+=1;if(b.base==16)f+=2}var
d=c;if(b.justify==M&&b.filler==s)for(var
e=f;e<b.width;e++)d+=s;if(b.signedconv)if(b.sign<0)d+=t;else
if(b.signstyle!=t)d+=b.signstyle;if(b.alternate&&b.base==8)d+=p;if(b.alternate&&b.base==16)d+="0x";if(b.justify==M&&b.filler==p)for(var
e=f;e<b.width;e++)d+=p;d+=g;if(b.justify==t)for(var
e=f;e<b.width;e++)d+=s;return a(d)}function
br(i,c){var
a,e=bz(i),d=e.prec<0?6:e.prec;if(c<0||c==0&&1/c==-Infinity){e.sign=-1;c=-c}if(isNaN(c)){a="nan";e.filler=s}else
if(!isFinite(c)){a="inf";e.filler=s}else
switch(e.conv){case"e":var
a=c.toExponential(d),b=a.length;if(a.charAt(b-3)==P)a=a.slice(0,b-1)+p+a.slice(b-1);break;case"f":a=c.toFixed(d);break;case"g":d=d?d:1;a=c.toExponential(d-1);var
h=a.indexOf(P),g=+a.slice(h+1);if(g<-4||c>=1e+21||c.toFixed(0).length>d){var
b=h-1;while(a.charAt(b)==p)b--;if(a.charAt(b)==N)b--;a=a.slice(0,b+1)+a.slice(h);b=a.length;if(a.charAt(b-3)==P)a=a.slice(0,b-1)+p+a.slice(b-1);break}else{var
f=d;if(g<0){f-=g+1;a=c.toFixed(f)}else
while(a=c.toFixed(f),a.length>d+1)f--;if(f){var
b=a.length-1;while(a.charAt(b)==p)b--;if(a.charAt(b)==N)b--;a=a.slice(0,b+1)}}break}return bq(e,a)}function
bK(g){for(var
h=c,b=h,a,j,d=0,i=g.length;d<i;d++){a=g.charCodeAt(d);if(a<f){for(var
e=d+1;e<i&&(a=g.charCodeAt(e))<f;e++);if(e-d>aF){b.substr(0,1);h+=b;b=c;h+=g.slice(d,e)}else
b+=g.slice(d,e);if(e==i)break;d=e}if(a<au){b+=String.fromCharCode(192|a>>6);b+=String.fromCharCode(f|a&63)}else
if(a<55296||a>=ay)b+=String.fromCharCode(ap|a>>12,f|a>>6&63,f|a&63);else
if(a>=56319||d+1==i||(j=g.charCodeAt(d+1))<aj||j>ay)b+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;b+=String.fromCharCode(at|a>>18,f|a>>12&63,f|a>>6&63,f|a&63)}if(b.length>x){b.substr(0,1);h+=b;b=c}}return h+b}function
G(a){var
b=9;if(!aL(a))b=8,a=bK(a);return new
n(b,a,a.length)}function
j(a){U(d.Sys_error,a)}var
o=new
Array();function
bt(e){var
a=o[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==c)return 0;if(a.fd&&d.fds[a.fd]&&d.fds[a.fd].output){var
b=d.fds[a.fd].output;switch(b.length){case
2:b(e,a.buffer);break;default:b(a.buffer)}}a.buffer=c;return 0}if(g.process&&g.process.cwd)var
y=g.process.cwd().replace(/\\/g,m);else
var
y="/static";if(y.slice(-1)!==m)y+=m;function
bs(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=y+a;var
e=a.split(m),b=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(c);break;default:b.push(e[d]);break}b.orig=a;return b}function
bA(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
bE(a){return new
n(4,a,a.length)}function
aO(){T("index out of bounds")}function
bG(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aP(b,a){if(a>>>0>=b.l)aO();return bG(b,a)}function
z(a){return a.l}function
aH(){}function
e(a){this.data=a}e.prototype=new
aH();e.prototype.truncate=function(a){var
b=this.data;this.data=q(a|0);u(b,0,this.data,0,a)};e.prototype.length=function(){return z(this.data)};e.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=q(b+a),f=this.data;this.data=e;u(f,0,this.data,0,c)}u(d,g,this.data,b,a);return 0};e.prototype.read=function(c,a,d,b){var
e=this.length();u(this.data,c,a,d,b);return 0};e.prototype.read_one=function(a){return aP(this.data,a)};e.prototype.close=function(){};e.prototype.constructor=e;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!=0)this.content[b]=new
e(c[1])}};h.prototype.exists=function(a){if(a==c)return 1;var
d=a+m,e=new
RegExp(O+d);for(var
b
in
this.content)if(b.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==c?c:d+m,h=new
RegExp(O+g+aw),e={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;b.push(a[1])}}return b};h.prototype.is_dir=function(a){var
e=a==c?c:a+m,f=new
RegExp(O+e+aw),g=[];for(var
d
in
this.content){var
b=d.match(f);if(b)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+ax);if(b.text&&b.binary)j(this.nm(a)+aq);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+as);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
e(q(0));return this.content[a]}else
bA(this.nm(a))};h.prototype.register=function(c,b){if(this.content[c])j(this.nm(c)+as);if(b
instanceof
n)this.content[c]=new
e(b);else
if(b
instanceof
Array)this.content[c]=new
e(bE(b));else
if(b.toString){var
d=a(b.toString());this.content[c]=new
e(d)}};h.prototype.constructor=h;function
aI(a){if(a.t!=4)S(a);return a.c}function
bH(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}S(a)}a.c[c]=b;return 0}function
bF(b,a,c){if(a>>>0>=b.l)aO();return bH(b,a,c)}var
Q=g.Buffer;function
l(a){this.fs=require("fs");this.fd=a}l.prototype=new
aH();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(f,b,c,e){var
a=aI(b);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
d=new
Q(a);this.fs.writeSync(this.fd,d,c,e,f);return 0};l.prototype.read=function(h,d,c,f){var
a=aI(d);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
e=new
Q(a);this.fs.readSync(this.fd,e,c,f,h);for(var
b=0;b<f;b++)bF(d,c+b,e[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(g.Uint8Array)(1),a=new
Q(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require("fs");this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
v=y.match(/[^\/]*\//)[0],A=[];if(typeof
module!=="undefined"&&module.exports&&typeof
require!=="undefined")A.push({path:v,device:new
k(v)});else
A.push({path:v,device:new
h(v)});A.push({path:v+al,device:new
h(v+al)});function
bO(b){var
f=bs(b),b=f.join(m),e=b+m,c;for(var
d=0;d<A.length;d++){var
a=A[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
aN(e,f){var
b=o[e],d=a(f),c=z(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
bL(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
bM(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
H(c,f,e,a){if(d.fds===undefined)d.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;d.fds[c]=b;if(!d.fd_last_idx||c>d.fd_last_idx)d.fd_last_idx=c;return c}function
bP(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(c.toString()+ax);if(a.text&&a.binary)j(c.toString()+aq);var
e=bO(c),f=e.device.open(e.rest,a),g=d.fd_last_idx?d.fd_last_idx:0;return H(g+1,aN,f,a)}H(0,aN,new
e(q(0)));H(1,bM,new
e(q(0)));H(2,bL,new
e(q(0)));function
bu(c){var
b=d.fds[c];if(b.flags.wronly)j(aC+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
aM(e){var
b=d.fds[e];if(b.flags.rdonly)j(aC+e+" is readonly");var
a={file:b.file,offset:b.offset,fd:e,opened:true,out:true,buffer:c};o[a.fd]=a;return a.fd}function
bv(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
bx(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(c,b,a){d[c+1]=b;if(a)d[a]=b}var
bw={};function
bC(a,b){bw[R(a)]=b;return 0}var
by=0;function
w(a){a[2]=by++;return a}function
L(a,b){return a.length==1?a(b):F(a,[b])}var
X=[b,a(aD),-3],Z=[b,a(an),-7];i(11,[b,a(ak),-12],ak);i(10,[b,a(ai),-11],ai);i(9,[b,a(aB),-10],aB);i(8,[b,a(ao),-9],ao);i(7,[b,a(am),-8],am);i(6,Z,an);i(5,[b,a(aA),-6],aA);i(4,[b,a(aE),-5],aE);i(3,[b,a(aG),-4],aG);i(2,X,aD);i(1,[b,a(az),-2],az);i(0,[b,a(ar),-1],ar);var
aS=a("%.12g"),aR=a(N),aQ=a("Pervasives.Exit"),aU=a("Array.Bottom"),aV=a("Sys.Break"),aW=a("CamlinternalFormat.Type_mismatch"),a0=a("Js.Error"),a4=a("input"),a3=a("button"),a2=a("Dom_html.Canvas_not_available"),bm=a("\xc2\xb0C"),bl=a("\xc2\xb0F"),bj=a(E),be=a(E),ba=a(E),a7=a(E),a5=a("clickme"),a8=a("count"),a_=a("textF"),bc=a("clickme2"),bf=a("count2"),bh=a("textF2");function
B(a){throw[0,X,a]}w([b,aQ,0]);function
I(d,c){var
a=z(d),e=z(c),b=q(a+e|0);u(d,0,b,0,a);u(c,0,b,a,e);return b}function
Y(e){var
b=br(aS,e),a=0,d=z(b);for(;;){if(d<=a)return I(b,aR);var
c=aP(b,a),f=48<=c?58<=c?0:1:45===c?1:0;if(f){var
a=a+1|0;continue}return b}}bu(0);aM(1);aM(2);w([b,aU,0]);w([b,aV,0]);w([b,aW,0]);var
_=[0,0];function
$(a){_[1]=[0,a,_[1]];return 0}var
J=g,C=null,aY=undefined;function
D(a,b){return a==C?L(b,0):a}var
aa=true,aZ=J.Array,ab=w([b,a0,0]),K=[0,ab,{}],aX=bx(K)===b?K:K[1];bC(a("jsError"),aX);(function(a){throw a});$(function(a){return a[1]===ab?[0,G(a[2].toString())]:0});$(function(a){return a
instanceof
aZ?0:[0,G(a.toString())]});function
ac(c){return function(a){if(1-(a==C?1:0)){var
d=L(c,a);if(1-(d|0))a.preventDefault();return d}var
e=event,b=L(c,e);if(1-(b|0))e.returnValue=b;return b}}var
a1=J.document;function
r(b){var
a=a1.getElementById(b.toString());if(a==C)throw Z;return a}w([b,a2,0]);J.HTMLElement===aY;function
ad(b,a){var
c=b.toString();return a.tagName.toLowerCase()===c?a:C}function
ae(a){return ad(a3,a)}function
af(a){return ad(a4,a)}var
ag=r(a5),a6=ae(ag);D(a6,function(a){return B(a7)});var
a9=r(a8),a$=af(r(a_)),bb=D(a$,function(a){return B(ba)}),ah=r(bc),bd=ae(ah);D(bd,function(a){return B(be)});var
bg=r(bf),bi=af(r(bh)),bk=D(bi,function(a){return B(bj)}),bn=ac(function(a){a9.innerHTML=I(Y(aK(G(bb.value))*av+32),bl).toString();return aa}),bo=ac(function(a){bg.innerHTML=I(Y((aK(G(bk.value))-32)/av),bm).toString();return aa});ag.onclick=bn;ah.onclick=bo;function
aT(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{bt(d)}catch(a){}var
a=c;continue}return 0}}aT(bv(0));return}(function(){return this}()));
