// Generated by js_of_ocaml 3.1.0
(function(g){"use strict";var
ak=" : flags Open_text and Open_binary are not compatible",Z="Sys_error",aj=224,ai="Invalid_argument",s=1024,Y=57343,ah=512,ag="End_of_file",af="Failure",W="Undefined_recursive_module",X=" : flags Open_rdonly and Open_wronly are not compatible",V="([^/]*)",ae="Stack_overflow",f=128,b="",D="^",R=" : file already exists",S=2048,T=56320,U=240,c=248,ad="Not_found",Q="Assert_failure",m="/",ab="Sys_blocked_io",ac="fd ",P="Out_of_memory",aa="Match_failure",_="Division_by_zero",$="static/";function
ap(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
a1(g){for(var
h=b,c=h,a,j,d=0,i=g.length;d<i;d++){a=g.charCodeAt(d);if(a<f){for(var
e=d+1;e<i&&(a=g.charCodeAt(e))<f;e++);if(e-d>ah){c.substr(0,1);h+=c;c=b;h+=g.slice(d,e)}else
c+=g.slice(d,e);if(e==i)break;d=e}if(a<S){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(f|a&63)}else
if(a<55296||a>=Y)c+=String.fromCharCode(aj|a>>12,f|a>>6&63,f|a&63);else
if(a>=56319||d+1==i||(j=g.charCodeAt(d+1))<T||j>Y)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;c+=String.fromCharCode(U|a>>18,f|a>>12&63,f|a>>6&63,f|a&63)}if(c.length>s){c.substr(0,1);h+=c;c=b}}return h+c}function
aT(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
a4(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
G(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=s,a-=s)f+=e.apply(null,a4(c,d,Math.min(a,s)));return f}function
an(a){if(a.t==2)a.c+=aT(a.l-a.c.length,"\0");else
a.c=G(a.c,0,a.c.length);a.t=0}function
a0(g){for(var
l=b,d=b,i,h,j,a,c=0,k=g.length;c<k;c++){h=g.charCodeAt(c);if(h<f){for(var
e=c+1;e<k&&(h=g.charCodeAt(e))<f;e++);if(e-c>ah){d.substr(0,1);l+=d;d=b;l+=g.slice(c,e)}else
d+=g.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(h<<6);if(h<aj){a=i-12416;if(a<f)a=1}else{a=2;if(++c<k&&((j=g.charCodeAt(c))&-64)==f){i=j+(i<<6);if(h<U){a=i-925824;if(a<S||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=g.charCodeAt(c))&-64)==f&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),T+(a&1023));else
d+=String.fromCharCode(a);if(d.length>s){d.substr(0,1);l+=d;d=b}}return l+d}function
aZ(a){switch(a.t){case
9:return a.c;default:an(a);case
0:if(ap(a.c)){a.t=9;return a.c}a.t=8;case
8:return a0(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return aZ(this)};function
aq(a){var
b=9;if(!ap(a))b=8,a=a1(a);return new
n(b,a,a.length)}function
aR(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
at(c,b){aR(c,a(b))}var
e=[0];function
j(a){at(e.Sys_error,a)}var
o=new
Array();function
aK(d){var
a=o[d];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&e.fds[a.fd]&&e.fds[a.fd].output){var
c=e.fds[a.fd].output;switch(c.length){case
2:c(d,a.buffer);break;default:c(a.buffer)}}a.buffer=b;return 0}if(g.process&&g.process.cwd)var
t=g.process.cwd().replace(/\\/g,m);else
var
t="/static";if(t.slice(-1)!==m)t+=m;function
aJ(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=t+a;var
e=a.split(m),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
aQ(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
aV(a){return new
n(4,a,a.length)}function
ao(a){at(e.Invalid_argument,a)}function
av(){ao("index out of bounds")}function
aX(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aU(b,a){if(a>>>0>=b.l)av();return aX(b,a)}function
p(a){if(a<0)ao("String.create");return new
n(a?2:9,b,a)}function
as(a){return a.l}function
F(b){if(g.Uint8Array)var
c=new(g.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
e=b.c,d=e.length,a=0;for(;a<d;a++)c[a]=e.charCodeAt(a);for(d=b.l;a<d;a++)c[a]=0;b.c=c;b.t=4;return c}function
w(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?G(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?G(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)F(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
al(){}function
d(a){this.data=a}d.prototype=new
al();d.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);w(b,0,this.data,0,a)};d.prototype.length=function(){return as(this.data)};d.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;w(f,0,this.data,0,c)}w(d,g,this.data,b,a);return 0};d.prototype.read=function(c,a,d,b){var
e=this.length();w(this.data,c,a,d,b);return 0};d.prototype.read_one=function(a){return aU(this.data,a)};d.prototype.close=function(){};d.prototype.constructor=d;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!=0)this.content[b]=new
d(c[1])}};h.prototype.exists=function(a){if(a==b)return 1;var
d=a+m,e=new
RegExp(D+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==b?b:d+m,h=new
RegExp(D+g+V),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};h.prototype.is_dir=function(a){var
e=a==b?b:a+m,f=new
RegExp(D+e+V),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+X);if(b.text&&b.binary)j(this.nm(a)+ak);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+R);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
d(p(0));return this.content[a]}else
aQ(this.nm(a))};h.prototype.register=function(c,b){if(this.content[c])j(this.nm(c)+R);if(b
instanceof
n)this.content[c]=new
d(b);else
if(b
instanceof
Array)this.content[c]=new
d(aV(b));else
if(b.toString){var
e=a(b.toString());this.content[c]=new
d(e)}};h.prototype.constructor=h;function
am(a){if(a.t!=4)F(a);return a.c}function
aY(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}F(a)}a.c[c]=b;return 0}function
aW(b,a,c){if(a>>>0>=b.l)av();return aY(b,a,c)}var
E=g.Buffer;function
l(a){this.fs=require("fs");this.fd=a}l.prototype=new
al();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(f,b,c,e){var
a=am(b);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
d=new
E(a);this.fs.writeSync(this.fd,d,c,e,f);return 0};l.prototype.read=function(h,d,c,f){var
a=am(d);if(!(a
instanceof
g.Uint8Array))a=new(g.Uint8Array)(a);var
e=new
E(a);this.fs.readSync(this.fd,e,c,f,h);for(var
b=0;b<f;b++)aW(d,c+b,e[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(g.Uint8Array)(1),a=new
E(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require("fs");this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
q=t.match(/[^\/]*\//)[0],u=[];if(typeof
module!=="undefined"&&module.exports&&typeof
require!=="undefined")u.push({path:q,device:new
k(q)});else
u.push({path:q,device:new
h(q)});u.push({path:q+$,device:new
h(q+$)});function
a5(b){var
f=aJ(b),b=f.join(m),e=b+m,c;for(var
d=0;d<u.length;d++){var
a=u[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
au(e,f){var
b=o[e],d=a(f),c=as(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
a2(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
a3(a){var
b=g;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
x(c,f,d,a){if(e.fds===undefined)e.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?d.length():0;b.flags=a;b.output=f;e.fds[c]=b;if(!e.fd_last_idx||c>e.fd_last_idx)e.fd_last_idx=c;return c}function
a6(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(c.toString()+X);if(a.text&&a.binary)j(c.toString()+ak);var
d=a5(c),f=d.device.open(d.rest,a),g=e.fd_last_idx?e.fd_last_idx:0;return x(g+1,au,f,a)}x(0,au,new
d(p(0)));x(1,a3,new
d(p(0)));x(2,a2,new
d(p(0)));function
aL(c){var
b=e.fds[c];if(b.flags.wronly)j(ac+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
ar(d){var
c=e.fds[d];if(c.flags.rdonly)j(ac+d+" is readonly");var
a={file:c.file,offset:c.offset,fd:d,opened:true,out:true,buffer:b};o[a.fd]=a;return a.fd}function
aM(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
aO(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(c,b,a){e[c+1]=b;if(a)e[a]=b}var
aN={};function
aI(a){if((a.t&6)!=0)an(a);return a.c}function
aS(a,b){aN[aI(a)]=b;return 0}var
aP=0;function
r(a){a[2]=aP++;return a}var
H=[c,a(af),-3],I=[c,a(ad),-7];i(11,[c,a(W),-12],W);i(10,[c,a(Q),-11],Q);i(9,[c,a(ab),-10],ab);i(8,[c,a(ae),-9],ae);i(7,[c,a(aa),-8],aa);i(6,I,ad);i(5,[c,a(_),-6],_);i(4,[c,a(ag),-5],ag);i(3,[c,a(ai),-4],ai);i(2,H,af);i(1,[c,a(Z),-2],Z);i(0,[c,a(P),-1],P);r([c,a("Pervasives.Exit"),0]);aL(0);ar(1);ar(2);r([c,a("Array.Bottom"),0]);r([c,a("Sys.Break"),0]);r([c,a("CamlinternalFormat.Type_mismatch"),0]);var
J=[0,0],aA=a("Js.Error"),aC=a("Dom_html.Canvas_not_available"),aH=a("erreur"),aD=a("btn_alert"),aE=a("click_number"),aG=a("btn_click");function
K(a){J[1]=[0,a,J[1]];return 0}var
y=g,v=null,L=true,az=y.Array,M=r([c,aA,0]),z=[0,M,{}],ay=undefined,ax=aO(z)===c?z:z[1];aS(a("jsError"),ax);(function(a){throw a});K(function(a){return a[1]===M?[0,aq(a[2].toString())]:0});K(function(a){return a
instanceof
az?0:[0,aq(a.toString())]});var
aB=y.document;function
A(b){var
a=aB.getElementById(b.toString());if(a==v)throw I;return a}r([c,aC,0]);y.HTMLElement===ay;A(aD);var
aF=A(aE),C=A(aG),N=C.tagName.toLowerCase()==="button"?C:v;if(N==v)throw[0,H,aH];var
B=[0,0];function
O(d){B[1]=B[1]+1|0;var
c=B[1];if(10===c)N.disabled=L;else
aF.innerHTML=a(b+c).toString();return L}C.onclick=function(a){if(1-(a==v?1:0)){var
c=O(a);if(1-(c|0))a.preventDefault();return c}var
d=event,b=O(d);if(1-(b|0))d.returnValue=b;return b};function
aw(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aK(d)}catch(a){}var
a=c;continue}return 0}}aw(aM(0));return}(function(){return this}()));
