// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


for(var x = 1; x <= 10; ++x){
  var x$1 = performance.now();
  alert("hello");
  var y = performance.now();
  alert(y - x$1);
}

/*  Not a pure module */
